[package]
name = "remarkable_lines"
description = "Remarkable Files Parser"
version = "0.1.1"
keywords = ["remarkable", "parser"]
authors = ["Lyr <lyr-7d1h@pm.me>"]
repository = "https://github.com/Lyr-7D1h/remarkable-lines"

license = "MIT"
edition = "2021"
rust-version="1.69.0"

[dependencies]
